#local_backend: true # Uncomment to use for local backend for development

backend:
  name: github
  branch: main
  repo: JTMurley/portfolio
  base_url: https://sveltia-cms-auth.jack-murley.workers.dev/

# These lines should *not* be indented
media_folder: "portfolio/static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads TODO: check this

collections:
- name: blog
  label: "blog"
  folder: portfolio/blog
  identifier_field: title
  extension: mdx
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"
    - label: "Authors"
      name: "authors"
      widget: "list"
      fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }